In [2]:
import numpy as np

In [5]:
np.absolute(-5)

5

In [2]:
# Generating numpy arrays

arr = np.array([1,2,3,4,5])
print(arr, type(arr), sep=", ")
print(arr.shape)

mat = np.array([[1,2,3,4],[5,6,7,8]])
print(mat, type(mat), sep=", ")
print(mat.shape)

print('mat[0][0]: {}, mat[1][2]: {}'.format(mat[0][0], mat[1][2]))

[1 2 3 4 5], <class 'numpy.ndarray'>
(5,)
[[1 2 3 4]
 [5 6 7 8]], <class 'numpy.ndarray'>
(2, 4)
mat[0][0]: 1, mat[1][2]: 7


In [9]:
# Taking dot product

a = np.array([[1,2],[3,4]])
print(a)
print(a.T)

dot_prod = np.dot(a, a.T)
print(dot_prod, type(dot_prod), sep=', ')

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[ 5 11]
 [11 25]], <class 'numpy.ndarray'>


In [10]:
# Finding maximum and minimum values

a = np.array([1,3,6,32,67,32,97,21,99,43,27])
min_a = np.min(a)
max_a = np.max(a)

print('Min is: {}'.format(min_a))
print('Max is: {}'.format(max_a))

Min is: 1
Max is: 99


In [18]:
# Find the most frequent number

a = np.array([1,7,3,9,3,5])
print('np.argmax(a) : {} , np.argmin(a) : {}'.format(np.argmax(a), np.argmin(a)))

a = np.array([1,6,5,1,6,4,4,7,8,2,2,3,1,2])
unique_a = np.unique(a)
print(unique_a)

unique_a = np.unique(a, return_counts = True)
idx = np.argmax(unique_a[1])
print(unique_a, idx, sep=' ; ')

most_frequent = unique_a[0][idx]
print('Most frequent number is: {}'.format(most_frequent))

np.argmax(a) : 3 , np.argmin(a) : 0
[1 2 3 4 5 6 7 8]
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([3, 3, 1, 2, 1, 2, 1, 1])) ; 0
Most frequent number is: 1


In [31]:
# Slicing in numpy arrays

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)

sliced_mat = a[1:3, 1:]
print('\nSliced matrix =\n', sliced_mat)

print('\nElement at a[1][3] =', a[1][3])

sliced_mat[:, 1:] = 0
print(sliced_mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Sliced matrix =
 [[ 6  7  8]
 [10 11 12]]

Element at a[1][3] = 8
[[ 6  0  0]
 [10  0  0]]


In [33]:
# Operations on all values of a numpy array with a constant

a = np.array([1,2,3,4,5])
print('Multiplying all elements by 2 =', a * 2)
print('Raise Power of all elements by 2 =', a ** 2)
print('Adding all elements by 2 =', a + 3)
print('Subtracting all elements by 2 =', a - 3)
print('Dividing all elements by 2 =', a / 3)
print('Int dividing all elements by 2 =', a // 3)
print('Xoring all elements by 2 =', a ^ 3)

Multiplying all elements by 2 = [ 2  4  6  8 10]
Raise Power of all elements by 2 = [ 1  4  9 16 25]
Adding all elements by 2 = [4 5 6 7 8]
Subtracting all elements by 2 = [-2 -1  0  1  2]
Dividing all elements by 2 = [0.33333333 0.66666667 1.         1.33333333 1.66666667]
Int dividing all elements by 2 = [0 0 1 1 1]
Xoring all elements by 2 = [2 1 0 7 6]


In [21]:
# Generating random numpy arrays

a = np.random.randint(1000)
print('np.random.randint(1000):', a)

a = np.random.randint(0, 1000, 5)
print('np.random.randint(0, 1000, 5):', a)

a = np.random.randint(60, 100, 5, dtype=int)
print('np.random.randint(60, 100, 5, dtype=int)', a)

a = np.random.randint(60, 100, (5,5))
print('np.random.randint(60, 100, (5,5))', a)

a = np.random.randint(60, 100, (2,2,2))
print('np.random.randint(60, 100, (2,2,2))', a)

np.random.randint(1000): 506
np.random.randint(0, 1000, 5): [546 992 419 519 339]
np.random.randint(60, 100, 5, dtype=int) [70 75 92 62 79]
np.random.randint(60, 100, (5,5)) [[63 79 73 70 76]
 [72 92 64 70 80]
 [94 81 77 78 63]
 [73 98 60 95 65]
 [98 75 84 95 68]]
np.random.randint(60, 100, (2,2,2)) [[[97 90]
  [67 97]]

 [[77 69]
  [65 81]]]


In [10]:
# Create an array of zeros or ones

a = np.zeros(4)
print(a)

a = np.zeros((4,))
print(a)

a = np.zeros((2,5))
print(a)

a = np.zeros((2,2,2))
print(a)

print('1s...')
a = np.ones(4)
print(a)

a = np.ones((4,))
print(a)

a = np.ones((2,5))
print(a)

a = np.ones((2,2,2))
print(a)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
1s...
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [11]:
# Array of constants

n = 3
m = 4
dp = np.full((n, m), -1)
print(dp)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [15]:
# Identity matrix

a = np.eye(3)
print(a)

a = np.eye(3, 4)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [28]:
# Random matrix
randomMatrix = np.random.random(3)
print('np.random.random(3) =>', randomMatrix)

randomMatrix = np.random.random((2,3))
print('np.random.random((2,3)) =>', randomMatrix)

randomMatrix[:, 1:] = 0.435
print('\nAfter updation: ', randomMatrix)

print(randomMatrix[:, 2:])

np.random.random(3) => [0.35874718 0.35760719 0.34841981]
np.random.random((2,3)) => [[0.04733281 0.68814467 0.09597732]
 [0.73272552 0.62920925 0.78880084]]

After updation:  [[0.04733281 0.435      0.435     ]
 [0.73272552 0.435      0.435     ]]
[[0.435]
 [0.435]]


In [41]:
# Data types of numpy arrays

z = np.random.random((2,3))
print('np.random.random((2,3)) =>', randomMatrix)
print(z.dtype)

a = np.ones((2,5))
print(a)
print(a.dtype)

a = np.random.randint(1, 100, (3, 2))
print('\nnp.random.randint:', a)
print(a.dtype)

a = np.random.randint(1, 99, (3, 2))
print('\nnp.random.randint:', a)
print(a.dtype)

a = np.random.randint(1, 10000000000000000, (3, 2), dtype=np.int64)
print('\nnp.random.randint:', a)
print(a.dtype)

np.random.random((2,3)) => [[0.04733281 0.435      0.435     ]
 [0.73272552 0.435      0.435     ]]
float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64

np.random.randint: [[53 86]
 [34 64]
 [98 88]]
int32

np.random.randint: [[64 70]
 [30 67]
 [97 41]]
int32

np.random.randint: [[1351753726850268 5621740567378798]
 [5213748364153463 3396650839591242]
 [9121461662288401 8417463073933338]]
int64


In [47]:
# Mathematical operations

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print('a + b = ', a + b)
print(np.add(a, b))

print('a - b = ', a - b)
print(np.subtract(a, b))

print('a * b = ', a * b)
print(np.multiply(a, b))

print('a / b = ', a / b)
print(np.divide(a, b))

a + b =  [[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
a - b =  [[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
a * b =  [[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
a / b =  [[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [48]:
# Square root

a = np.array([1, 2, 3, 4])
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.        ]


In [7]:
# Dot product of two matrices

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x, y, sep='\n')

print(x.dot(y))
print(np.dot(x, y))

x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[5,6,7],[7,8,9]])

print(x, y, sep='\n')

print(x.dot(y))
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 2]
 [3 4]
 [5 6]]
[[5 6 7]
 [7 8 9]]
[[19 22 25]
 [43 50 57]
 [67 78 89]]
[[19 22 25]
 [43 50 57]
 [67 78 89]]


In [8]:
# Multiplication of vectors gives a scalar

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(x, y, sep='\n')

print(x.dot(y))
print(np.dot(x, y))

[1 2 3 4]
[5 6 7 8]
70
70


In [12]:
# Sum of an numpy array

x = np.array([[1,2],[3,4]])
print(x)
print('Sum of elements of x: ', sum(x))
print('Sum of elements of x: ', np.sum(x))

print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1 2]
 [3 4]]
Sum of elements of x:  [4 6]
Sum of elements of x:  10
[4 6]
[3 7]


In [16]:
# Stacking of arrays

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
z = np.stack((x, y), axis=0)
print(x, y, z, sep='\n')

z = np.stack((x, y), axis=1)
print(z, sep='\n')

[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [18]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.stack((x, y), axis=0)
print(x, y, z, z.shape, sep='\n')

z = np.stack((x, y), axis=1)
print(z, z.shape, sep='\n')

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)
