# CHALLENGE - DIABETES DETECTION

---

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
dfX = pd.read_csv('./Training_Data/Diabetes_XTrain.csv')
dfY = pd.read_csv('./Training_Data/Diabetes_YTrain.csv')

In [5]:
dfX.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            7      168             88             42      321  38.2   
1            8      110             76              0        0  27.8   
2            7      147             76              0        0  39.4   
3            2      100             66             20       90  32.9   
4            4      129             86             20      270  35.1   

   DiabetesPedigreeFunction  Age  
0                     0.787   40  
1                     0.237   58  
2                     0.257   43  
3                     0.867   28  
4                     0.231   23

In [6]:
dfY.head()

Outcome
0        1
1        0
2        1
3        1
4        0

In [7]:
print(dfX.shape)
print(dfY.shape)

(576, 8)
(576, 1)


In [8]:
X = dfX.values
y = dfY.values

In [9]:
print(X.shape)
print(y.shape)

(576, 8)
(576, 1)


In [10]:
X

array([[  7.   , 168.   ,  88.   , ...,  38.2  ,   0.787,  40.   ],
       [  8.   , 110.   ,  76.   , ...,  27.8  ,   0.237,  58.   ],
       [  7.   , 147.   ,  76.   , ...,  39.4  ,   0.257,  43.   ],
       ...,
       [  2.   , 122.   ,  60.   , ...,  29.8  ,   0.717,  22.   ],
       [  4.   , 154.   ,  72.   , ...,  31.3  ,   0.338,  37.   ],
       [  1.   ,  88.   ,  78.   , ...,  32.   ,   0.365,  29.   ]])

In [13]:
print(type(y))
print(y)

<class 'numpy.ndarray'>
[[1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 

In [14]:
trainset = np.concatenate((X, y), axis = 1)

In [17]:
dfTrain = pd.DataFrame(trainset)

In [18]:
dfTrain.shape

(576, 9)

In [19]:
dfTrain.head()

0      1     2     3      4     5      6     7    8
0  7.0  168.0  88.0  42.0  321.0  38.2  0.787  40.0  1.0
1  8.0  110.0  76.0   0.0    0.0  27.8  0.237  58.0  0.0
2  7.0  147.0  76.0   0.0    0.0  39.4  0.257  43.0  1.0
3  2.0  100.0  66.0  20.0   90.0  32.9  0.867  28.0  1.0
4  4.0  129.0  86.0  20.0  270.0  35.1  0.231  23.0  0.0

In [20]:
trainset

array([[  7.   , 168.   ,  88.   , ...,   0.787,  40.   ,   1.   ],
       [  8.   , 110.   ,  76.   , ...,   0.237,  58.   ,   0.   ],
       [  7.   , 147.   ,  76.   , ...,   0.257,  43.   ,   1.   ],
       ...,
       [  2.   , 122.   ,  60.   , ...,   0.717,  22.   ,   0.   ],
       [  4.   , 154.   ,  72.   , ...,   0.338,  37.   ,   0.   ],
       [  1.   ,  88.   ,  78.   , ...,   0.365,  29.   ,   0.   ]])

### Load the test data

In [21]:
dfTest = pd.read_csv('./Test_Cases/Diabetes_Xtest.csv')

In [22]:
dfTest.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            0      180             90             26       90  36.5   
1            2       93             64             32      160  38.0   
2            2      114             68             22        0  28.7   
3           13       76             60              0        0  32.8   
4            1       80             74             11       60  30.0   

   DiabetesPedigreeFunction  Age  
0                     0.314   35  
1                     0.674   23  
2                     0.092   25  
3                     0.180   41  
4                     0.527   22

In [24]:
test = dfTest.values

In [25]:
test.shape

(192, 8)

In [28]:
test[0]

array([  0.   , 180.   ,  90.   ,  26.   ,  90.   ,  36.5  ,   0.314,
        35.   ])

## KNN Algorithm

In [32]:
def dist(x1, x2):
    return np.sqrt(sum((x1 - x2) ** 2))

def knn(train, query_pt, k=5):
    vals = []
    
    
    Y = train[:, -1]
    X = train[:, :-1]
    m = X.shape[0]
    
    for i in range(m):
        d = dist(X[i], query_pt)
        vals.append([d, Y[i]])
        
    vals = sorted(vals)
    
    vals = np.array(vals)
    vals = vals[:k, :]
    
    counts = np.unique(vals[:, 1], return_counts=True)
    idx = counts[1].argmax()
    pred = counts[0][idx]
    return pred

### Make Predictions

In [30]:
print(trainset.shape)
print(test.shape)
test[0].shape

(576, 9)
(192, 8)


(8,)

In [37]:
labels = []
m = test.shape[0]

for i in range(m):
    pred = knn(trainset, test[i])
    labels.append(int(pred))

In [38]:
len(labels)

192

In [40]:
labels = np.asarray(labels)

In [41]:
labels.shape

(192,)

In [42]:
labels

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0])

In [43]:
dfLabels = pd.DataFrame(labels, dtype = 'int32', columns = ['Outcome'])
dfLabels.head()

Outcome
0        1
1        0
2        0
3        0
4        0

In [44]:
dfLabels.to_csv('output.csv', index = False)

In [46]:
all_labels = []
for j in range(1, 11):
    labels = []
    m = test.shape[0]

    for i in range(m):
        pred = knn(trainset, test[i], j)
        labels.append(int(pred))
    labels = np.asarray(labels)
    all_labels.append(labels)
    dfLabels = pd.DataFrame(labels, dtype = 'int32', columns = ['Outcome'])
    dfLabels.to_csv('outputnew' + str(j) + '.csv', index = False)

In [48]:
a = np.concatenate(all_labels, axis = 1)

In [56]:
b = np.vstack(all_labels)

In [58]:
all_labels

[array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
        1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
        1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
        0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0

In [69]:
for i in range(len(all_labels)):
    all_labels[i] = all_labels[i].reshape((192, 1))

In [70]:
all_labels[0].shape

(192, 1)

In [72]:
g = np.concatenate(all_labels, axis = 1)

In [73]:
g

array([[1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [74]:
g.shape

(192, 10)

In [75]:
dfAllLabels = pd.DataFrame(g)

In [77]:
print(dfAllLabels)

     0  1  2  3  4  5  6  7  8  9
0    1  1  1  1  1  0  1  1  1  1
1    0  0  0  0  0  0  0  0  0  0
2    0  0  0  0  0  0  0  0  0  0
3    0  0  0  0  0  0  0  0  0  0
4    0  0  0  0  0  0  0  0  0  0
..  .. .. .. .. .. .. .. .. .. ..
187  1  1  1  1  1  1  1  1  1  0
188  0  0  0  0  0  0  1  0  0  0
189  0  0  1  1  1  1  1  1  1  1
190  0  0  0  0  1  1  1  0  0  0
191  0  0  0  0  0  0  0  0  0  0

[192 rows x 10 columns]
